Hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Incluye las URLs de tu aplicación de reservas
    path('', include('reservas.urls')),  # Las URLs de la app estarán en la raíz    
    
]

reservas/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', auth_views.LoginView.as_view() , name='home1'),
    path('home/', views.home, name='home'),
    
    # Clientes
    path('clientes/', views.lista_clientes, name='clientes'),
    path('clientes/nuevo/', views.crear_cliente, name='crear_cliente'),
    path('clientes/editar/<int:pk>/', views.editar_cliente, name='editar_cliente'),
    path('clientes/eliminar/<int:pk>/', views.eliminar_cliente, name='eliminar_cliente'),

    # Habitaciones
    path('habitaciones/', views.lista_habitaciones, name='habitaciones'),
    path('habitaciones/nueva/', views.crear_habitacion, name='crear_habitacion'),
    path('habitaciones/editar/<int:pk>/', views.editar_habitacion, name='editar_habitacion'),
    path('habitaciones/eliminar/<int:pk>/', views.eliminar_habitacion, name='eliminar_habitacion'),

    # Tipo de habitaciones
    path('habitaciones/nuevotipo/', views.crear_tipohabitacion, name='crear_tipohabitacion'),

    # Reservas
    path('reservas/', views.lista_reservas, name='reservas'),
    path('reservar/', views.crear_reserva, name='reservar'),
    path('reservas/eliminar/<int:pk>/', views.eliminar_reserva, name='eliminar_reserva'),
    path('reservas/editar/<int:pk>/', views.editar_reserva, name='editar_reserva'),
    
    #Descargar Reservas en pdf y excel
    path('reporte-reservas/pdf/', views.reporte_reservas_pdf, name='reporte_reservas_pdf'),
    path('reporte-reservas/excel/', views.reporte_reservas_excel, name='reporte_reservas_excel'),
    
    # Autenticación
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.salir, name='logout'),
    path('accounts/registro/', views.registrar, name='registrar'),
]

reservas/models.py
from django.db import models

class Cliente(models.Model):
    id_cliente = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    telefono = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"


class TipoHabitacion(models.Model):
    id_tipo_habitacion = models.AutoField(primary_key=True)
    nombre_tipo = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)
    precio_noche = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nombre_tipo


class Habitacion(models.Model):
    id_habitacion = models.AutoField(primary_key=True)  # Opcional, Django lo crea automáticamente
    numero_habitacion = models.CharField(max_length=10)
    tipo_habitacion = models.ForeignKey(TipoHabitacion, on_delete=models.CASCADE)
    capacidad = models.IntegerField()
    estado = models.CharField(
        max_length=1, 
        choices=[('D','Disponible'), ('O','Ocupada'), ('M','Mantenimiento')], 
        default='D'
    )

    def __str__(self):
        return f"Habitación {self.numero_habitacion}"


class Reserva(models.Model):
    id_reserva = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)  # Quitar db_column para evitar problemas
    habitacion = models.ForeignKey(Habitacion, on_delete=models.CASCADE)  # Igual aquí
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    estado_reserva = models.CharField(
        max_length=20,
        choices=[
            ('confirmada', 'Confirmada'),
            ('pendiente', 'Pendiente'),
            ('cancelada', 'Cancelada'),
            ('completada', 'Completada'),
        ],
        default='pendiente'
    )

    def __str__(self):
        return f"Reserva {self.id_reserva} - {self.cliente} en {self.habitacion}"

reservas/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Cliente, Habitacion, Reserva, TipoHabitacion
from datetime import date
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import os
from django.conf import settings

class RegistroUsuarioForm(UserCreationForm):
    nombre = forms.CharField(max_length=100, required=True)
    apellido = forms.CharField(max_length=100, required=True)
    telefono = forms.CharField(max_length=20, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'apellido', 'email', 'telefono']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
        }


class TipoHabitacionForm(forms.ModelForm):
    class Meta:
        model = TipoHabitacion
        fields = ['nombre_tipo', 'descripcion', 'precio_noche']
        widgets = {
            'nombre_tipo': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'precio_noche': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class HabitacionForm(forms.ModelForm):
    class Meta:
        model = Habitacion
        fields = ['numero_habitacion', 'tipo_habitacion', 'capacidad', 'estado']
        widgets = {
            'numero_habitacion': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_habitacion': forms.Select(attrs={'class': 'form-control'}),
            'capacidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
        }


class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['cliente', 'habitacion', 'fecha_inicio', 'fecha_fin']
        widgets = {
            'cliente': forms.Select(attrs={'class': 'form-control'}),
            'habitacion': forms.Select(attrs={'class': 'form-control'}),
            'fecha_inicio': forms.DateInput(
                format='%d/%m/%Y',
                attrs={'class': 'form-control', 'placeholder': 'DIA/MES/AÑO', 'type': 'text'}
            ),
            'fecha_fin': forms.DateInput(
                format='%d/%m/%Y',
                attrs={'class': 'form-control', 'placeholder': 'DIA/MES/AÑO', 'type': 'text'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fecha_inicio'].input_formats = ['%d/%m/%Y']
        self.fields['fecha_fin'].input_formats = ['%d/%m/%Y']

    def clean(self):
        cleaned_data = super().clean()
        fecha_inicio = cleaned_data.get('fecha_inicio')
        fecha_fin = cleaned_data.get('fecha_fin')
        habitacion = cleaned_data.get('habitacion')

        if fecha_inicio and fecha_fin:
            if fecha_inicio < date.today():
                raise ValidationError("No se pueden hacer reservas en fechas pasadas.")
            if fecha_fin <= fecha_inicio:
                raise ValidationError("La fecha de salida debe ser posterior a la de entrada.")

        if habitacion and fecha_inicio and fecha_fin:
            reservas_solapadas = Reserva.objects.filter(
                habitacion=habitacion,
                estado_reserva='confirmada',
                fecha_inicio__lt=fecha_fin,
                fecha_fin__gt=fecha_inicio
            )
            if self.instance.pk:
                reservas_solapadas = reservas_solapadas.exclude(pk=self.instance.pk)

            if reservas_solapadas.exists():
                raise ValidationError("La habitación no está disponible para esas fechas.")


class DisponibilidadForm(forms.Form):
    fecha_inicio = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    fecha_fin = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    tipo_habitacion = forms.ModelChoiceField(
        queryset=TipoHabitacion.objects.all(),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    def clean(self):
        cleaned_data = super().clean()
        fecha_inicio = cleaned_data.get('fecha_inicio')
        fecha_fin = cleaned_data.get('fecha_fin')

        if fecha_inicio and fecha_fin:
            if fecha_fin <= fecha_inicio:
                raise ValidationError("La fecha de fin debe ser posterior a la fecha de inicio.")

reservas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cliente, Habitacion, Reserva, TipoHabitacion
from .forms import ReservaForm, HabitacionForm, ClienteForm, TipoHabitacionForm
from .forms import RegistroUsuarioForm
from .models import Cliente
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from openpyxl import Workbook

def es_admin(user):
    return user.is_staff

# REGISTRAR (público)
def registrar(request):
    if request.method == 'POST':
        form = RegistroUsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Crear cliente asociado
            Cliente.objects.create(
                nombre=form.cleaned_data['nombre'],
                apellido=form.cleaned_data['apellido'],
                email=form.cleaned_data['email'],
                telefono=form.cleaned_data['telefono']
            )
            login(request, user)
            return redirect('home')
    else:
        form = RegistroUsuarioForm()
    return render(request, 'registration/registrar.html', {'form': form})

# LOGIN / LOGOUT
def salir(request):
    logout(request)
    return redirect('home1')

def home(request):
    return render(request, 'home.html')

# MODELOS
def inicio(request):
    return render(request, 'inicio.html')

# CLIENTES
@login_required
def lista_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'clientes.html', {'clientes': clientes})

@login_required
@user_passes_test(es_admin)
def crear_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clientes')
    else:
        form = ClienteForm()
    return render(request, 'crear_cliente.html', {'form': form})

@login_required
@user_passes_test(es_admin)
def editar_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'editar_cliente.html', {'form': form, 'cliente': cliente})

@login_required
@user_passes_test(es_admin)
def eliminar_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clientes')
    return render(request, 'eliminar_cliente.html', {'cliente': cliente})

# TIPO DE HABITACIONES
@login_required
@user_passes_test(es_admin)
def crear_tipohabitacion(request):
    if request.method == 'POST':
        form = TipoHabitacionForm(request.POST)
        if form.is_valid():
            tipo_habitacion = form.save(commit=False)  # Mantengo tu nombre de variable
            tipo_habitacion.imagen = form.cleaned_data.get('imagen')
            tipo_habitacion.save()
            return redirect('habitaciones')
    else:
        form = TipoHabitacionForm()
    return render(request, 'crear_tipohabitacion.html', {'form': form})

# HABITACIONES
@login_required
def lista_habitaciones(request):
    habitaciones = Habitacion.objects.all()
    return render(request, 'habitaciones.html', {'habitaciones': habitaciones})

@login_required
@user_passes_test(es_admin)
def crear_habitacion(request):
    if request.method == 'POST':
        form = HabitacionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('habitaciones')
    else:
        form = HabitacionForm()
    return render(request, 'crear_habitacion.html', {'form': form})

@login_required
@user_passes_test(es_admin)
def editar_habitacion(request, pk):
    habitacion = get_object_or_404(Habitacion, pk=pk)
    if request.method == 'POST':
        form = HabitacionForm(request.POST, instance=habitacion)
        if form.is_valid():
            form.save()
            return redirect('habitaciones')
    else:
        form = HabitacionForm(instance=habitacion)
    return render(request, 'editar_habitacion.html', {'form': form, 'habitacion': habitacion})

@login_required
@user_passes_test(es_admin)
def eliminar_habitacion(request, pk):
    habitacion = get_object_or_404(Habitacion, pk=pk)
    if request.method == 'POST':
        habitacion.delete()
        return redirect('habitaciones')
    return render(request, 'eliminar_habitacion.html', {'habitacion': habitacion})

# RESERVAS
@login_required
def lista_reservas(request):
    reservas = Reserva.objects.all()
    return render(request, 'reservas.html', {'reservas': reservas})

@login_required
def crear_reserva(request):
    habitaciones = Habitacion.objects.all()
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            habitacion = form.cleaned_data['habitacion']
            fecha_inicio = form.cleaned_data['fecha_inicio']
            fecha_fin = form.cleaned_data['fecha_fin']

            # Verificar estado de la habitación
            if habitacion.estado != 'D':  # 'D' para Disponible
                messages.error(request, 'La habitación no está disponible para reservar.')
                return render(request, 'reservar.html', {'form': form})

            # Verificar que no haya reservas solapadas
            solapamiento = Reserva.objects.filter(
                habitacion=habitacion,
                fecha_fin__gte=fecha_inicio,
                fecha_inicio__lte=fecha_fin
            ).exists()

            if solapamiento:
                messages.error(request, 'La habitación ya está reservada en esas fechas.')
                return render(request, 'reservar.html', {'form': form})

            # Si pasa todas las validaciones, guardar reserva
            form.save()
            messages.success(request, 'Reserva creada con éxito.')
            return redirect('reservas')
    else:
        form = ReservaForm()
    return render(request, 'reservar.html', {'form': form, 'habitaciones': habitaciones})

@login_required
@user_passes_test(es_admin)
def editar_reserva(request, pk):
    reserva = get_object_or_404(Reserva, pk=pk)
    if request.method == 'POST':
        form = ReservaForm(request.POST, instance=reserva)
        if form.is_valid():
            form.save()
            return redirect('reservas')
    else:
        form = ReservaForm(instance=reserva)
    return render(request, 'editar_reserva.html', {'form': form, 'reserva': reserva})

@login_required
@user_passes_test(es_admin)
def eliminar_reserva(request, pk):
    reserva = get_object_or_404(Reserva, pk=pk)
    if request.method == 'POST':
        reserva.delete()
        return redirect('reservas')
    return render(request, 'eliminar_reserva.html', {'reserva': reserva})

# DESCARGAR RESERVAS

# PDF
def reporte_reservas_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="reservas.pdf"'

    p = canvas.Canvas(response, pagesize=letter)
    width, height = letter

    p.setFont("Helvetica-Bold", 16)
    p.drawString(200, height - 50, "Lista de Reservas")

    p.setFont("Helvetica", 11)
    y = height - 80

    reservas = Reserva.objects.all()

    for reserva in reservas:
        texto = f"{reserva.cliente.nombre} {reserva.cliente.apellido} | Habitación: {reserva.habitacion.numero_habitacion} | {reserva.fecha_inicio} → {reserva.fecha_fin}"
        p.drawString(50, y, texto)
        y -= 20
        if y < 50:  # Salto de página
            p.showPage()
            y = height - 50

    p.save()
    return response


# EXCEL
def reporte_reservas_excel(request):
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename="reservas.xlsx"'

    wb = Workbook()
    ws = wb.active
    ws.title = "Reservas"

    ws.append(["Cliente", "Habitación", "Fecha Inicio", "Fecha Fin"])

    reservas = Reserva.objects.all()

    for r in reservas:
        ws.append([
            f"{r.cliente.nombre} {r.cliente.apellido}",
            r.habitacion.numero_habitacion,
            str(r.fecha_inicio),
            str(r.fecha_fin)
        ])

    wb.save(response)
    return response

reservas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Sistema de Reservas{% endblock %}</title>
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/reserva.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar-container">
            {% if request.user.is_authenticated %}
                {% if request.user.is_staff %}
                    <a href="{% url 'clientes' %}">Clientes</a>
                {% endif %}
                <a href="{% url 'home' %}">Inicio</a>
                <a href="{% url 'habitaciones' %}">Habitaciones</a>
                <a href="{% url 'reservas' %}">Reservas</a>
                <a href="{% url 'logout' %}">Salir</a>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}
    {% endblock %}
</body>
</html>

reservas/templates/clientes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Clientes{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/estiloClientes.css' %}">

    <div class="container">
        <h2>Lista de Clientes</h2>
        <table>
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Email</th>
                    {% if request.user.is_staff %}
                        <th>Acciones</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                    <tr>
                        <td data-label="Nombre">{{ cliente.nombre }} {{ cliente.apellido }}</td>
                        <td data-label="Email">{{ cliente.email }}</td>
                        {% if request.user.is_staff %}
                            <td data-label="Acciones">
                                <a href="{% url 'editar_cliente' cliente.id_cliente %}">
                                    <button>Editar</button>
                                </a>
                                <a href="{% url 'eliminar_cliente' cliente.id_cliente %}">
                                    <button style="background: #c00;">Eliminar</button>
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="{% if request.user.is_staff %}3{% else %}2{% endif %}">No hay clientes registrados</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if request.user.is_staff %}
        <div class="add-client-button-container">
            <a href="{% url 'crear_cliente' %}">
                <button>+ Añadir Cliente</button>
            </a>
        </div>
        {% endif %}
    </div>
{% endblock %}

reservas/templates/crear_habitacion.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nueva Habitación{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/crudHabi.css' %}">
<h2>Nueva Habitación</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Guardar Habitación</button>
    <a href="{% url 'habitaciones' %}"><button type="button">Cancelar</button></a>
</form>
{% endblock %}

reservas/templates/crear_tipohabitacion.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nuevo Tipo de Habitación{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/crudHabi.css' %}">
<h2>Nuevo Tipo de Habitación</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Guardar Tipo de Habitación</button>
    <a href="{% url 'habitaciones' %}"><button type="button">Cancelar</button></a>
</form>
{% endblock %}

reservas/templates/editar_cliente.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Editar Cliente{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/crudCliED.css' %}">
<h2>Editar Cliente</h2>

<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
    <a href="{% url 'clientes' %}"><button type="button">Cancelar</button></a>
</form>
{% endblock %}

reservas/templates/editar_habitacion.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Editar Habitación{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/crudHabiED.css' %}">
<h2>Editar Habitación</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
    <a href="{% url 'habitaciones' %}"><button type="button">Cancelar</button></a>
</form>
{% endblock %}

reservas/templates/habitaciones.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Habitaciones{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/estiloHabitaciones.css' %}">

    <div class="container">
        <h2>Lista de Habitaciones</h2>
        <table>
            <thead>
                <tr>
                    <th>Número</th>
                    <th>Tipo</th>
                    <th>Precio/Noche</th>
                    <th>Estado</th>
                    {% if request.user.is_staff %}
                    <th>Acciones</th>
                    {% else %}
                    <th>Descripción</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for habitacion in habitaciones %}
                <tr>
                    <td data-label="Número">{{ habitacion.numero_habitacion }}</td>
                    <td data-label="Tipo">{{ habitacion.tipo_habitacion.nombre_tipo }}</td>
                    <td data-label="Precio/Noche">${{ habitacion.tipo_habitacion.precio_noche }}</td>
                    <td data-label="Estado">{{ habitacion.get_estado_display }}</td>
                    {% if request.user.is_staff %}
                    <td data-label="Acciones">
                        <a href="{% url 'editar_habitacion' habitacion.id_habitacion %}"><button>Editar</button></a>
                        <a href="{% url 'eliminar_habitacion' habitacion.id_habitacion %}"><button style="background-color: #c00;">Eliminar</button></a>
                    </td>
                    {% else %}
                    <td data-label="Descripción">{{ habitacion.tipo_habitacion.descripcion }}</td>
                    {% endif %}
                </tr>
                {% empty %}
                <tr>
                    <td colspan="{% if request.user.is_staff %}5{% else %}4{% endif %}">No hay habitaciones registradas</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if request.user.is_authenticated and request.user.is_staff %}
        <div class="action-buttons-container">
            <div>
                <a href="{% url 'crear_tipohabitacion' %}">
                    <button>+ Nuevo tipo de habitación</button>
                </a>
            </div>
            <div>
                <a href="{% url 'crear_habitacion' %}">
                    <button>+ Nueva Habitación</button>
                </a>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

reservas/templates/reservar.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Nueva Reserva{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/carrusel.css' %}">

<script>
     document.addEventListener('DOMContentLoaded', function() {
    const track = document.getElementById('mediumCarouselTrack');
    let currentIndex = 0;
    const items = document.querySelectorAll('.carousel-item');
    
    function moveCarousel() {
      currentIndex = (currentIndex + 1) % items.length;
      track.style.transform = `translateX(-${currentIndex * 100}%)`;
    }

    setInterval(moveCarousel, 3500);
    
    track.addEventListener('mouseenter', () => clearInterval(interval));
    track.addEventListener('mouseleave', () => interval = setInterval(moveCarousel, 3500));
  });
</script>

<div class="reserva-container">
    <div class="reserva-formulario">
        <h2>{% if reserva %}Editar{% else %}Nueva{% endif %} Reserva</h2>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_cliente">Cliente:</label>
                {{ form.cliente.errors }}
                {{ form.cliente }}
            </div>
            <div class="form-group">
                <label for="id_habitacion">Habitación:</label>
                {{ form.habitacion.errors }}
                {{ form.habitacion }}
            </div>
            <div class="form-group">
                <label for="id_fecha_inicio">Fecha de Entrada:</label>
                {{ form.fecha_inicio.errors }}
                {{ form.fecha_inicio }}
            </div>
            <div class="form-group">
                <label for="id_fecha_fin">Fecha de Salida:</label>
                {{ form.fecha_fin.errors }}
                {{ form.fecha_fin }}
            </div>
            <button type="submit" class="btn btn-success">Guardar Reserva</button>
            <a href="{% url 'reservas' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
    <div class="medium-carousel">
  <div class="carousel-track" id="mediumCarouselTrack">
    <div class="carousel-item">
      <img src="{% static 'img/doble1.jpg' %}" alt="Habitación Doble">
      <p class="image-caption">Habitación Doble</p>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/familiar2.jpg' %}" alt="Habitación Familiar">
      <p class="image-caption">Habitación Familiar</p>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/individual2.jpg' %}" alt="Habitación Individual">
      <p class="image-caption">Habitación Individual</p>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/triple1.jpg' %}" alt="Habitación Triple">
      <p class="image-caption">Habitación Triple</p>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/suite2.jpg' %}" alt="Suite Ejecutiva">
      <p class="image-caption">Suite Ejecutiva</p>
    </div>
  </div>
</div>
</div>
{% endblock %}